language: java
os: osx
osx_image: xcode9.3
install:
- ./configure-key.sh
- mvn clean > maven_phase1.log
script:
- mvn test -B > maven_phase2.log
- mvn pmd:check pmd:cpd-check
after_success: 
- chmod ugo+x push.sh
- ./push.sh
after_failure:
- chmod ugo+x push.sh
- ./push.sh
