language: java
os: osx
osx_image: xcode9.3
install:
- mvn clean > maven_phase1.log
script:
- mvn test -B > maven_phase2.log
- mvn pmd:pmd pmd:cpd
after_success: 
- chmod ugo+x push.sh
- ./push.sh
after_failure:
- chmod ugo+x push.sh
- ./push.sh
